services:
  mirofish:
    image: ghcr.io/666ghj/mirofish:latest
    # 加速镜像（如拉取缓慢可替换上方地址）
    # image: ghcr.nju.edu.cn/666ghj/mirofish:latest
    container_name: mirofish
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-3001}:${FRONTEND_PORT:-3001}"
      - "${FLASK_PORT:-5001}:${FLASK_PORT:-5001}"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads